/**
 * Dados de exemplo para demonstração do painel.
 *
 * Datas são geradas relativas ao dia em que o exemplo é carregado, para que
 * os cenários de risco (férias vencendo, aprovações atrasadas, processos
 * parados) continuem fazendo sentido em qualquer época.
 */

import type { Banco } from "../types";
import { VERSAO_BANCO } from "../types";
import { hojeISO, somarDias, somarMeses } from "./datas";

export function bancoExemplo(): Banco {
  const hoje = hojeISO();

  return {
    versao: VERSAO_BANCO,
    atualizadoEm: new Date().toISOString(),
    pessoas: [
      {
        id: "p1",
        nome: "Ana Beatriz Souza",
        email: "ana.souza@empresa.com.br",
        cargo: "Analista Comercial",
        area: "Comercial",
        nivel: "Analista Sênior",
        regime: "CLT",
        dataAdmissao: somarMeses(hoje, -40),
        salario: 8500,
        gestorId: null,
        status: "Ativo",
        atribuicoes: [
          "Consolidar sell-in/sell-out das regionais",
          "Manter cadastro de clientes e políticas comerciais",
          "Apoiar fechamento mensal de metas",
        ],
        observacoes: "",
      },
      {
        id: "p2",
        nome: "Carlos Eduardo Lima",
        email: "carlos.lima@empresa.com.br",
        cargo: "Coordenador de Logística",
        area: "Logística",
        nivel: "Coordenador",
        regime: "CLT",
        dataAdmissao: somarMeses(hoje, -30),
        salario: 12000,
        gestorId: null,
        status: "Ativo",
        atribuicoes: [
          "Gestão da transportadora e frete",
          "Nível de serviço de entrega (OTIF)",
          "Controle de estoque do CD",
        ],
        observacoes: "Férias do período anterior ainda em aberto — priorizar.",
      },
      {
        id: "p3",
        nome: "Fernanda Oliveira",
        email: "fernanda.oliveira@empresa.com.br",
        cargo: "Analista Financeiro",
        area: "Financeiro",
        nivel: "Analista Pleno",
        regime: "CLT",
        dataAdmissao: somarMeses(hoje, -20),
        salario: 6800,
        gestorId: null,
        status: "Férias",
        atribuicoes: [
          "Contas a pagar e conciliação bancária",
          "Fluxo de caixa semanal",
          "Apoio ao orçamento anual",
        ],
        observacoes: "",
      },
      {
        id: "p4",
        nome: "João Pedro Martins",
        email: "joao.martins@empresa.com.br",
        cargo: "Assistente Administrativo",
        area: "Administrativo",
        nivel: "Assistente",
        regime: "CLT",
        dataAdmissao: somarMeses(hoje, -7),
        salario: 3200,
        gestorId: "p2",
        status: "Ativo",
        atribuicoes: ["Compras administrativas", "Gestão de contratos de facilities"],
        observacoes: "Em período de aquisição do primeiro ciclo de férias.",
      },
      {
        id: "p5",
        nome: "Mariana Castro",
        email: "mariana.castro@empresa.com.br",
        cargo: "Analista de Marketing",
        area: "Marketing",
        nivel: "Analista Júnior",
        regime: "PJ",
        dataAdmissao: somarMeses(hoje, -14),
        salario: 5500,
        gestorId: "p1",
        status: "Ativo",
        atribuicoes: ["Redes sociais e conteúdo", "Materiais de trade marketing"],
        observacoes: "PJ — férias por acordo contratual, não CLT.",
      },
    ],
    ferias: [
      {
        id: "f1",
        pessoaId: "p1",
        inicio: somarMeses(hoje, -9),
        dias: 20,
        status: "Gozada",
        diasVendidos: 0,
        observacao: "Primeiro fracionamento do período.",
      },
      {
        id: "f2",
        pessoaId: "p3",
        inicio: somarDias(hoje, -10),
        dias: 15,
        status: "Aprovada",
        diasVendidos: 0,
        observacao: "Em gozo agora.",
      },
      {
        id: "f3",
        pessoaId: "p1",
        inicio: somarDias(hoje, 45),
        dias: 10,
        status: "Planejada",
        diasVendidos: 0,
        observacao: "Fecha o período aquisitivo.",
      },
    ],
    processos: [
      {
        id: "pr1",
        nome: "Fechamento mensal de vendas",
        area: "Comercial",
        descricao: "Consolidação de sell-in/sell-out por regional e canal, com análise de metas.",
        donoId: "p1",
        backupId: null,
        frequencia: "Mensal",
        criticidade: "Crítica",
        entregavel: "Relatório de fechamento no Power BI",
        prazo: "Todo dia 5 útil",
        indicador: "Prazo de entrega do fechamento",
        meta: "Até D+5",
        status: "Em dia",
        ultimaExecucao: somarDias(hoje, -12),
        documentado: true,
        link: "",
      },
      {
        id: "pr2",
        nome: "Roteirização e expedição",
        area: "Logística",
        descricao: "Programação diária de cargas e acompanhamento das entregas.",
        donoId: "p2",
        backupId: "p4",
        frequencia: "Diária",
        criticidade: "Crítica",
        entregavel: "Cargas expedidas no prazo",
        prazo: "Corte às 15h",
        indicador: "OTIF",
        meta: "≥ 95%",
        status: "Em risco",
        ultimaExecucao: hoje,
        documentado: false,
        link: "",
      },
      {
        id: "pr3",
        nome: "Fluxo de caixa semanal",
        area: "Financeiro",
        descricao: "Projeção de caixa 13 semanas com posição consolidada de bancos.",
        donoId: "p3",
        backupId: null,
        frequencia: "Semanal",
        criticidade: "Alta",
        entregavel: "Planilha de fluxo 13 semanas",
        prazo: "Toda segunda até 12h",
        indicador: "Acurácia da projeção (sem. 1)",
        meta: "≥ 90%",
        status: "Atrasado",
        ultimaExecucao: somarDias(hoje, -16),
        documentado: true,
        link: "",
      },
      {
        id: "pr4",
        nome: "Compras administrativas",
        area: "Administrativo",
        descricao: "Cotação, aprovação e emissão de pedidos de material e serviços internos.",
        donoId: "p4",
        backupId: null,
        frequencia: "Sob demanda",
        criticidade: "Média",
        entregavel: "Pedido emitido com 3 cotações",
        prazo: "48h da solicitação",
        indicador: "Lead time de compra",
        meta: "≤ 48h",
        status: "Em dia",
        ultimaExecucao: somarDias(hoje, -3),
        documentado: false,
        link: "",
      },
      {
        id: "pr5",
        nome: "Calendário de conteúdo",
        area: "Marketing",
        descricao: "Planejamento e publicação de conteúdo nas redes e trade.",
        donoId: "p5",
        backupId: null,
        frequencia: "Semanal",
        criticidade: "Baixa",
        entregavel: "Calendário aprovado da semana seguinte",
        prazo: "Sexta até 17h",
        indicador: "Posts no prazo",
        meta: "100%",
        status: "Em dia",
        ultimaExecucao: somarDias(hoje, -4),
        documentado: true,
        link: "",
      },
    ],
    aprovacoes: [
      {
        id: "a1",
        tipo: "Viagem",
        solicitanteId: "p1",
        descricao: "Visita a clientes-chave em Recife — 2 diárias + aéreo",
        valor: 2850,
        dataSolicitacao: somarDias(hoje, -6),
        prazoResposta: somarDias(hoje, -1),
        status: "Pendente",
        dataDecisao: null,
        centroCusto: "Comercial",
        link: "",
        observacao: "",
      },
      {
        id: "a2",
        tipo: "Mobilidade (Uber/táxi)",
        solicitanteId: "p5",
        descricao: "Corridas do mês — ações de trade em campo",
        valor: 412.6,
        dataSolicitacao: somarDias(hoje, -3),
        prazoResposta: somarDias(hoje, 2),
        status: "Pendente",
        dataDecisao: null,
        centroCusto: "Marketing",
        link: "",
        observacao: "",
      },
      {
        id: "a3",
        tipo: "Reembolso de despesa",
        solicitanteId: "p2",
        descricao: "Pedágio e alimentação — acompanhamento de rota",
        valor: 187.9,
        dataSolicitacao: somarDias(hoje, -1),
        prazoResposta: somarDias(hoje, 4),
        status: "Pendente",
        dataDecisao: null,
        centroCusto: "Logística",
        link: "",
        observacao: "",
      },
      {
        id: "a4",
        tipo: "Orçamento",
        solicitanteId: "p3",
        descricao: "Revisão orçamentária Q3 — reforço em frete",
        valor: 85000,
        dataSolicitacao: somarDias(hoje, -8),
        prazoResposta: somarDias(hoje, 7),
        status: "Em análise",
        dataDecisao: null,
        centroCusto: "Logística",
        link: "",
        observacao: "Aguardando parecer do financeiro.",
      },
      {
        id: "a5",
        tipo: "Compra / Contrato",
        solicitanteId: "p4",
        descricao: "Renovação contrato de limpeza — 12 meses",
        valor: 36000,
        dataSolicitacao: somarDias(hoje, -15),
        prazoResposta: somarDias(hoje, -10),
        status: "Aprovado",
        dataDecisao: somarDias(hoje, -11),
        centroCusto: "Administrativo",
        link: "",
        observacao: "",
      },
      {
        id: "a6",
        tipo: "Mobilidade (Uber/táxi)",
        solicitanteId: null,
        descricao: "Revisão semanal — corridas Uber Business da equipe",
        valor: 0,
        dataSolicitacao: somarDias(hoje, -2),
        prazoResposta: somarDias(hoje, 2),
        status: "Pendente",
        dataDecisao: null,
        centroCusto: "Comercial",
        link: "https://business.uber.com/",
        observacao:
          "Abrir o link, revisar as corridas da semana no Uber e registrar a decisão aqui — a próxima semana entra na fila sozinha.",
        recorrenciaDias: 7,
      },
    ],
    avaliacoes: [
      {
        id: "av1",
        pessoaId: "p1",
        ciclo: "2026-S1",
        competencias: { entrega: 5, qualidade: 4, colaboracao: 5, autonomia: 4, lideranca: 4 },
        resultado: 5,
        potencial: 3,
        data: somarDias(hoje, -30),
        pontosFortes: "Domínio do fechamento, referência para o time.",
        pontosDesenvolver: "Delegar mais; formar backup no processo de fechamento.",
        planoAcao: "Treinar Mariana como backup até o fim do trimestre.",
      },
      {
        id: "av2",
        pessoaId: "p2",
        ciclo: "2026-S1",
        competencias: { entrega: 4, qualidade: 4, colaboracao: 3, autonomia: 5, lideranca: 4 },
        resultado: 4,
        potencial: 2,
        data: somarDias(hoje, -28),
        pontosFortes: "Autonomia total na operação, resolve sem escalar.",
        pontosDesenvolver: "Comunicação com o comercial em rupturas.",
        planoAcao: "Ritual semanal de alinhamento logística × comercial.",
      },
      {
        id: "av3",
        pessoaId: "p3",
        ciclo: "2026-S1",
        competencias: { entrega: 4, qualidade: 5, colaboracao: 4, autonomia: 3, lideranca: 2 },
        resultado: 4,
        potencial: 2,
        data: somarDias(hoje, -25),
        pontosFortes: "Precisão técnica, zero retrabalho na conciliação.",
        pontosDesenvolver: "Antecipar problemas em vez de reportar depois.",
        planoAcao: "Assumir apresentação do fluxo de caixa na reunião mensal.",
      },
      {
        id: "av4",
        pessoaId: "p4",
        ciclo: "2026-S1",
        competencias: { entrega: 3, qualidade: 3, colaboracao: 4, autonomia: 2, lideranca: 2 },
        resultado: 3,
        potencial: 3,
        data: somarDias(hoje, -20),
        pontosFortes: "Aprende rápido, boa relação com fornecedores.",
        pontosDesenvolver: "Autonomia nas cotações; ainda depende de validação.",
        planoAcao: "Alçada própria até R$ 2 mil a partir do próximo mês.",
      },
      {
        id: "av5",
        pessoaId: "p5",
        ciclo: "2026-S1",
        competencias: { entrega: 4, qualidade: 4, colaboracao: 5, autonomia: 3, lideranca: 3 },
        resultado: 3,
        potencial: 3,
        data: somarDias(hoje, -18),
        pontosFortes: "Criatividade e velocidade de produção.",
        pontosDesenvolver: "Medir resultado das campanhas, não só entregar peça.",
        planoAcao: "Definir 3 KPIs de conteúdo com o comercial.",
      },
    ],
  };
}
